/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2019, The Linux Foundation. All rights reserved.
 */

#define CONFIG_TOUCHPANEL_ONEPLUS 1
#define CONFIG_TOUCHPANEL_GOODIX 1
#define CONFIG_TOUCHPANEL_GOODIX_GT9886 1
#define CONFIG_TOUCHPANEL_SAMSUNG 1
#define CONFIG_TOUCHPANEL_SAMSUNG_S6SY761 1
#define CONFIG_TOUCHPANEL_COMMON 1
#define CONFIG_INPUT_FINGERPRINT 1
#define CONFIG_FINGERPRINT_DETECT 1
#define CONFIG_FINGERPRINT_GOODIX 1
